import { FileText, Loader2, Save, Shield, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { deletePolicePatrolReport, getGuildLiveOptions, getPolicePatrolDashboard, savePolicePatrolSettings } from "../../lib/api";
import type { DashboardGuild, GuildCategoryOption, GuildChannelOption, GuildRoleOption, PolicePatrolDashboard, PolicePatrolSettings } from "../../types";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../ui/card";
import { Switch } from "../ui/switch";
import { FivemResourceMultiSelect } from "./FivemResourceSelect";

export function PolicePatrolReportsPanel({ botId, canManage, guild }: { botId?: string | null; canManage: boolean; guild: DashboardGuild | null }) {
  const [data, setData] = useState<PolicePatrolDashboard | null>(null); const [channels, setChannels] = useState<GuildChannelOption[]>([]); const [categories, setCategories] = useState<GuildCategoryOption[]>([]); const [roles, setRoles] = useState<GuildRoleOption[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { if (!botId || !guild) { setLoading(false); return; } let mounted = true; setLoading(true); Promise.all([getPolicePatrolDashboard(guild.id, botId), getGuildLiveOptions(guild.id, botId)]).then(([dashboard, options]) => { if (!mounted) return; setData(dashboard); setChannels(options.channels); setCategories(options.categories ?? []); setRoles(options.roles); }).catch((error) => mounted && setMessage(readMessage(error))).finally(() => mounted && setLoading(false)); return () => { mounted = false; }; }, [botId, guild?.id]);
  const stats = useMemo(() => { const reports = data?.reports ?? []; return { total: reports.length, finished: reports.filter((item) => item.status === "finished").length, minutes: reports.reduce((sum, item) => sum + (item.durationMinutes ?? 0), 0), officers: new Set(reports.map((item) => item.officerId)).size }; }, [data]);
  if (!botId || !guild) return <Empty text="Selecione um bot e servidor para configurar relatórios policiais." />; if (loading || !data) return <Empty loading text="Carregando relatórios policiais..." />;
  const patch = (next: Partial<PolicePatrolSettings>) => setData((current) => current ? { ...current, settings: { ...current.settings, ...next } } : current);
  async function save() { setSaving(true); setMessage(null); try { const settings = await savePolicePatrolSettings(guild!.id, botId!, data!.settings); setData((current) => current ? { ...current, settings } : current); setMessage("Configurações policiais salvas."); } catch (error) { setMessage(readMessage(error)); } finally { setSaving(false); } }
  async function remove(reportId: string) { if (!confirm("Excluir permanentemente este relatório e todas as mensagens?")) return; setSaving(true); try { await deletePolicePatrolReport(guild!.id, botId!, reportId); setData((current) => current ? { ...current, reports: current.reports.filter((item) => item.id !== reportId) } : current); } catch (error) { setMessage(readMessage(error)); } finally { setSaving(false); } }
  return <div className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Shield className="h-5 w-5 text-blue-300" />Relatórios de Patrulhamento</CardTitle><CardDescription>Módulo exclusivo da Polícia. Use /relatorio e /vrelatorio no Discord.</CardDescription></CardHeader></Card>
    {message ? <div className="rounded-lg border border-blue-500/30 bg-blue-500/10 p-3 text-sm text-white">{message}</div> : null}
    <div className="grid gap-3 sm:grid-cols-4"><Metric label="Relatórios" value={stats.total} /><Metric label="Finalizados" value={stats.finished} /><Metric label="Policiais" value={stats.officers} /><Metric label="Tempo patrulhado" value={`${Math.floor(stats.minutes / 60)}h${stats.minutes % 60}m`} /></div>
    <Card><CardHeader><CardTitle>Permissões e canais</CardTitle><CardDescription>Todos os cargos e recursos abaixo pertencem somente ao sistema policial.</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2">
      <FivemResourceMultiSelect disabled={!canManage} label="Cargos que criam relatórios" options={roles} values={data.settings.creatorRoleIds} onChange={(creatorRoleIds) => patch({ creatorRoleIds })} />
      <FivemResourceMultiSelect disabled={!canManage} label="Cargos que visualizam todos" options={roles} values={data.settings.viewerRoleIds} onChange={(viewerRoleIds) => patch({ viewerRoleIds })} />
      <FivemResourceMultiSelect disabled={!canManage} label="Cargos que excluem" options={roles} values={data.settings.deleteRoleIds} onChange={(deleteRoleIds) => patch({ deleteRoleIds })} />
      <FivemResourceMultiSelect disabled={!canManage} label="Cargos de supervisão nos canais" options={roles} values={data.settings.supervisorRoleIds} onChange={(supervisorRoleIds) => patch({ supervisorRoleIds })} />
      <FivemResourceMultiSelect disabled={!canManage} label="Canais do /relatorio" options={channels} values={data.settings.commandChannelIds ?? (data.settings.commandChannelId ? [data.settings.commandChannelId] : [])} onChange={(commandChannelIds) => patch({ commandChannelIds, commandChannelId: commandChannelIds[0] ?? null })} />
      <FivemResourceMultiSelect disabled={!canManage} label="Canais de logs" options={channels} values={data.settings.logChannelIds ?? (data.settings.logChannelId ? [data.settings.logChannelId] : [])} onChange={(logChannelIds) => patch({ logChannelIds, logChannelId: logChannelIds[0] ?? null })} />
      <FivemResourceMultiSelect disabled={!canManage} label="Categorias dos canais temporários" options={categories} values={data.settings.temporaryCategoryIds ?? (data.settings.temporaryCategoryId ? [data.settings.temporaryCategoryId] : [])} onChange={(temporaryCategoryIds) => patch({ temporaryCategoryIds, temporaryCategoryId: temporaryCategoryIds[0] ?? null })} />
      <FivemResourceMultiSelect disabled={!canManage} label="Categorias de arquivo" options={categories} values={data.settings.archiveCategoryIds ?? (data.settings.archiveCategoryId ? [data.settings.archiveCategoryId] : [])} onChange={(archiveCategoryIds) => patch({ archiveCategoryIds, archiveCategoryId: archiveCategoryIds[0] ?? null })} />
      <FivemResourceMultiSelect disabled={!canManage} label="Cargos que podem ver o canal arquivado" options={roles} values={data.settings.archiveViewRoleIds} onChange={(archiveViewRoleIds) => patch({ archiveViewRoleIds })} />
      <label className="text-sm text-zinc-300">Excluir canal após (minutos)<input className="mt-2 h-11 w-full rounded-lg border border-zinc-800 bg-black px-3" type="number" min={0} max={1440} disabled={!canManage} value={data.settings.deleteDelayMinutes} onChange={(event) => patch({ deleteDelayMinutes: Number(event.target.value) })} /></label>
      <label className="text-sm text-zinc-300">Exportação padrão<select className="mt-2 h-11 w-full rounded-lg border border-zinc-800 bg-black px-3" disabled={!canManage} value={data.settings.defaultExportFormat} onChange={(event) => patch({ defaultExportFormat: event.target.value as PolicePatrolSettings["defaultExportFormat"] })}><option value="html">HTML</option><option value="pdf">PDF</option><option value="json">JSON</option></select></label>
      <div className="flex items-center justify-between gap-3 lg:col-span-2"><label className="flex items-center gap-2"><Switch checked={data.settings.enabled} disabled={!canManage} onCheckedChange={(enabled) => patch({ enabled })} />Sistema policial ativo</label><Button disabled={!canManage || saving} onClick={() => void save()}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Salvar</Button></div>
    </CardContent></Card>
    <Card><CardHeader><CardTitle>Histórico policial</CardTitle><CardDescription>Relatórios persistidos, inclusive rascunhos e cancelados.</CardDescription></CardHeader><CardContent className="space-y-2">{data.reports.map((report) => <div className="flex flex-col gap-3 rounded-lg border border-zinc-800 p-3 sm:flex-row sm:items-center sm:justify-between" key={report.id}><div className="min-w-0"><p className="truncate font-semibold text-white"><FileText className="mr-2 inline h-4 w-4" />{report.officerName}</p><p className="text-xs text-zinc-500">por {report.authorName} · {new Date(report.createdAt).toLocaleString("pt-BR")} · {report.messageCount} mensagens · {report.attachmentCount} anexos</p></div><div className="flex items-center gap-2"><Badge variant={report.status === "finished" ? "success" : report.status === "cancelled" ? "danger" : "muted"}>{status(report.status)}</Badge>{canManage ? <Button size="icon" variant="destructive" disabled={saving} onClick={() => void remove(report.id)}><Trash2 className="h-4 w-4" /></Button> : null}</div></div>)}{!data.reports.length ? <p className="py-8 text-center text-zinc-500">Nenhum relatório policial registrado.</p> : null}</CardContent></Card>
  </div>;
}
function Empty({ text, loading = false }: { text: string; loading?: boolean }) { return <Card><CardContent className="flex min-h-48 items-center justify-center gap-2 text-zinc-400">{loading ? <Loader2 className="h-5 w-5 animate-spin" /> : null}{text}</CardContent></Card>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <Card><CardContent className="p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-xl font-bold text-white">{value}</p></CardContent></Card>; }
function status(value: string) { return ({ draft: "Rascunho", active: "Em andamento", finished: "Finalizado", cancelled: "Cancelado" } as Record<string, string>)[value] ?? value; }
function readMessage(error: unknown) { return (error as any)?.response?.data?.message ?? "Não foi possível concluir a operação."; }
