import { Router } from "express";
import { advancedModulesRouter } from "./advancedModules";
import { antiBanBotRouter, antiBanDashboardRouter } from "./antiBan";
import { authRouter } from "./auth";
import { automatedLogsRouter } from "./automatedLogs";
import { botDevApiRouter } from "./botDevApi";
import { clipsRouter } from "./clips";
import { communicationRouter } from "./communication";
import { dashboardRouter } from "./dashboard";
import { databaseMaintenanceRouter } from "./databaseMaintenance";
import { devRouter } from "./dev";
import { emojiClonerRouter } from "./emojiCloner";
import { fivemRouter } from "./fivem";
import { fivemActionsRouter } from "./fivemActions";
import { fivemFinanceRouter } from "./fivemFinance";
import { globalBlacklistRouter } from "./globalBlacklist";
import { giveawaysRouter } from "./giveaways";
import { guildsRouter } from "./guilds";
import { healthRouter } from "./health";
import { imageAntiSpamRouter } from "./imageAntiSpam";
import { kickNotificationsRouter, kickWebhookRouter } from "./kickNotifications";
import { livesRouter } from "./lives";
import { logsRouter } from "./logs";
import { manualRegistrationRouter } from "./manualRegistration";
import { manualPaymentsRouter } from "./manualPayments";
import { fivemOrdersRouter } from "./fivemOrders";
import { missionToolsRouter } from "./missionTools";
import { orvitechSalesRouter } from "./orvitechSales";
import { openPointNotificationsRouter } from "./openPointNotifications";
import { mediaRouter } from "./media";
import { panelImagesRouter } from "./panelImages";
import { policePatrolReportsRouter } from "./policePatrolReports";
import { policeCoursesRouter } from "./policeCourses";
import { priceTablesRouter } from "./priceTables";
import { persistentImagesRouter } from "./persistentImages";
import { selfBotProtectionRouter } from "./selfBotProtection";
import { serverBackupsRouter } from "./serverBackups";
import { settingsRouter } from "./settings";
import { botLivesRouter, socialNotificationsRouter } from "./socialNotifications";
import { socialsRouter } from "./socials";
import { ticketsRouter } from "./tickets";
import { temporaryVoiceRouter } from "./temporaryVoice";
import { usersRouter } from "./users";
import { voiceRecorderRouter } from "./voiceRecorder";
import { xMonitorRouter } from "./xMonitor";
import { xWebhookRouter } from "./xWebhook";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/_shardcloud/health", healthRouter);
apiRouter.use("/advanced-modules", advancedModulesRouter);
apiRouter.use("/anti-ban", antiBanBotRouter);
apiRouter.use("/image-anti-spam", imageAntiSpamRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/automated-logs", automatedLogsRouter);
apiRouter.use("/bot", botDevApiRouter);
apiRouter.use("/bots", botLivesRouter);
apiRouter.use("/bots", antiBanDashboardRouter);
apiRouter.use("/clips", clipsRouter);
apiRouter.use("/communication", communicationRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/database-maintenance", databaseMaintenanceRouter);
apiRouter.use("/dev", devRouter);
apiRouter.use("/emoji-cloner", emojiClonerRouter);
apiRouter.use("/fivem", fivemRouter);
apiRouter.use("/fivem-actions", fivemActionsRouter);
apiRouter.use("/fivem-finance", fivemFinanceRouter);
apiRouter.use("/global-blacklist", globalBlacklistRouter);
apiRouter.use("/giveaways", giveawaysRouter);
apiRouter.use("/kick", kickWebhookRouter);
apiRouter.use("/kick-integration", kickNotificationsRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/guilds", guildsRouter);
apiRouter.use("/lives", livesRouter);
apiRouter.use("/mission-tools", missionToolsRouter);
apiRouter.use("/orvitech-sales", orvitechSalesRouter);
apiRouter.use("/open-point-notifications", openPointNotificationsRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/panel-images", panelImagesRouter);
apiRouter.use("/police-patrol-reports", policePatrolReportsRouter);
apiRouter.use("/police-courses", policeCoursesRouter);
apiRouter.use("/price-tables", priceTablesRouter);
apiRouter.use("/persistent-images", persistentImagesRouter);
apiRouter.use("/tickets", ticketsRouter);
apiRouter.use("/temporary-voice", temporaryVoiceRouter);
apiRouter.use("/voice-recorder", voiceRecorderRouter);
apiRouter.use("/logs", logsRouter);
apiRouter.use("/manual-registration", manualRegistrationRouter);
apiRouter.use("/manual-payments", manualPaymentsRouter);
apiRouter.use("/fivem-orders", fivemOrdersRouter);
apiRouter.use("/self-bot-protection", selfBotProtectionRouter);
apiRouter.use("/server-backups", serverBackupsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/social-notifications", socialNotificationsRouter);
apiRouter.use("/socials", socialsRouter);
apiRouter.use("/x-monitor", xMonitorRouter);
apiRouter.use("/x-webhook", xWebhookRouter);
