import { raw, Router } from "express";
import { z } from "zod";
import { requireAuth, requireBot } from "../middleware/auth";
import { canReadDevBotModule, canUseDevBotModule, getBotApiPermissions } from "../services/devBotService";
import {
    appendPolicePatrolMessage, cancelPolicePatrolReport, clearPolicePatrolChannel, createPolicePatrolReport,
    deletePolicePatrolReport, finishPolicePatrolReport,
    getPolicePatrolFile,
    getPolicePatrolReport, getPolicePatrolReportByChannel,
    getPolicePatrolSettings,
    listPolicePatrolChannelsDue, listPolicePatrolReports, POLICE_PATROL_MODULE_ID,
    savePolicePatrolFile,
    savePolicePatrolSettings,
    setPolicePatrolChannel, startPolicePatrolReport
} from "../services/policePatrolReportService";
import { resolveRequestBotId } from "../services/requestBotScopeService";

const snowflake = z.string().regex(/^\d{5,32}$/); const id = z.string().uuid();
const settingsSchema = z.object({ enabled: z.boolean().optional(), creatorRoleIds: z.array(snowflake).max(100).optional(), viewerRoleIds: z.array(snowflake).max(100).optional(), deleteRoleIds: z.array(snowflake).max(100).optional(), supervisorRoleIds: z.array(snowflake).max(100).optional(), logChannelId: snowflake.nullable().optional(), temporaryCategoryId: snowflake.nullable().optional(), archiveCategoryId: snowflake.nullable().optional(), archiveViewRoleIds: z.array(snowflake).max(100).optional(), deleteDelayMinutes: z.coerce.number().int().min(0).max(1440).optional(), defaultExportFormat: z.enum(["html", "pdf", "json"]).optional() });
export const policePatrolReportsRouter = Router();

policePatrolReportsRouter.get("/files/:fileId", requireAuth, async (req, res, next) => { try { const file = await getPolicePatrolFile(id.parse(req.params.fileId)); if (!file) throw routeError("Arquivo não encontrado.", 404); await authorize(res.locals.dashboardAuth.user, file.botId, file.guildId, false); res.setHeader("Content-Type", file.mimeType || "application/octet-stream"); res.setHeader("Content-Length", String(file.size)); res.setHeader("Content-Disposition", `inline; filename*=UTF-8''${encodeURIComponent(file.name)}`); res.send(file.buffer); } catch (error) { next(error); } });
policePatrolReportsRouter.put("/bot/reports/:reportId/files/:attachmentId", requireBot, raw({ type: () => true, limit: "30mb" }), async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); if (!Buffer.isBuffer(req.body) || !req.body.length) throw routeError("Arquivo vazio.", 400); const name = z.string().min(1).max(255).parse(req.header("x-file-name")); const mimeType = z.string().min(1).max(200).parse(req.header("content-type") ?? "application/octet-stream"); res.status(201).json({ file: await savePolicePatrolFile(botId, id.parse(req.params.reportId), { discordAttachmentId: snowflake.parse(req.params.attachmentId), name, mimeType, buffer: req.body }) }); } catch (error) { next(error); } });

policePatrolReportsRouter.get("/:guildId", requireAuth, async (req, res, next) => { try { const guildId = snowflake.parse(req.params.guildId); const botId = await botIdFor(req); await authorize(res.locals.dashboardAuth.user, botId, guildId, false); res.json({ settings: await getPolicePatrolSettings(botId, guildId), reports: await listPolicePatrolReports(botId, guildId, null, 250) }); } catch (error) { next(error); } });
policePatrolReportsRouter.patch("/:guildId/settings", requireAuth, async (req, res, next) => { try { const guildId = snowflake.parse(req.params.guildId); const botId = await botIdFor(req); await authorize(res.locals.dashboardAuth.user, botId, guildId, true); res.json({ settings: await savePolicePatrolSettings(botId, guildId, settingsSchema.parse(req.body), res.locals.dashboardAuth.user.discordId) }); } catch (error) { next(error); } });
policePatrolReportsRouter.get("/:guildId/reports/:reportId", requireAuth, async (req, res, next) => { try { const guildId = snowflake.parse(req.params.guildId); const botId = await botIdFor(req); await authorize(res.locals.dashboardAuth.user, botId, guildId, false); res.json(await getPolicePatrolReport(botId, id.parse(req.params.reportId))); } catch (error) { next(error); } });
policePatrolReportsRouter.delete("/:guildId/reports/:reportId", requireAuth, async (req, res, next) => { try { const guildId = snowflake.parse(req.params.guildId); const botId = await botIdFor(req); await authorize(res.locals.dashboardAuth.user, botId, guildId, true); const report = await deletePolicePatrolReport(botId, id.parse(req.params.reportId), res.locals.dashboardAuth.user.discordId); if (!report) throw routeError("Relatório não encontrado.", 404); res.json({ report }); } catch (error) { next(error); } });

policePatrolReportsRouter.get("/bot/:guildId/settings", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); res.json({ settings: await getPolicePatrolSettings(botId, snowflake.parse(req.params.guildId)) }); } catch (error) { next(error); } });
policePatrolReportsRouter.post("/bot/reports", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); const input = z.object({ guildId: snowflake, officerId: snowflake, officerName: z.string().max(100), authorId: snowflake, authorName: z.string().max(100), patrolType: z.string().max(100).nullable().optional(), initialNotes: z.string().max(1000).nullable().optional() }).parse(req.body); res.status(201).json({ report: await createPolicePatrolReport({ botId, ...input }) }); } catch (error) { next(error); } });
policePatrolReportsRouter.patch("/bot/reports/:reportId/channel", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); const input = z.object({ channelId: snowflake, panelMessageId: snowflake }).parse(req.body); res.json({ report: await setPolicePatrolChannel(botId, id.parse(req.params.reportId), input.channelId, input.panelMessageId) }); } catch (error) { next(error); } });
policePatrolReportsRouter.post("/bot/reports/:reportId/start", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); const input = z.object({ actorId: snowflake, patrolStart: z.string(), patrolEnd: z.string() }).parse(req.body); res.json({ report: await startPolicePatrolReport(botId, id.parse(req.params.reportId), input.actorId, input.patrolStart, input.patrolEnd) }); } catch (error) { next(error); } });
policePatrolReportsRouter.post("/bot/reports/:reportId/messages", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); const input = z.object({ discordMessageId: snowflake, authorId: snowflake, content: z.string().max(10000), attachments: z.array(z.object({ id: snowflake, name: z.string().max(255), url: z.string().max(2048), contentType: z.string().nullable(), size: z.number().int().nonnegative() })).max(25), embeds: z.array(z.unknown()).max(10), stickers: z.array(z.object({ id: snowflake, name: z.string().max(100), format: z.number().int() })).max(10), emojis: z.array(z.string().max(100)).max(100), createdAt: z.coerce.date() }).parse(req.body); res.status(201).json({ message: await appendPolicePatrolMessage(botId, id.parse(req.params.reportId), input) }); } catch (error) { next(error); } });
policePatrolReportsRouter.post("/bot/reports/:reportId/finish", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); const input = z.object({ actorId: snowflake, deleteDelayMinutes: z.number().int().min(0).max(1440) }).parse(req.body); res.json(await finishPolicePatrolReport(botId, id.parse(req.params.reportId), input.actorId, input.deleteDelayMinutes)); } catch (error) { next(error); } });
policePatrolReportsRouter.post("/bot/reports/:reportId/cancel", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); const input = z.object({ actorId: snowflake, deleteDelayMinutes: z.number().int().min(0).max(1440) }).parse(req.body); res.json({ report: await cancelPolicePatrolReport(botId, id.parse(req.params.reportId), input.actorId, input.deleteDelayMinutes) }); } catch (error) { next(error); } });
policePatrolReportsRouter.get("/bot/reports/channel/:channelId", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); res.json({ report: await getPolicePatrolReportByChannel(botId, snowflake.parse(req.params.channelId)) }); } catch (error) { next(error); } });
policePatrolReportsRouter.get("/bot/reports/:reportId", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); res.json(await getPolicePatrolReport(botId, id.parse(req.params.reportId))); } catch (error) { next(error); } });
policePatrolReportsRouter.get("/bot/:guildId/reports", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); res.json({ reports: await listPolicePatrolReports(botId, snowflake.parse(req.params.guildId), typeof req.query.officerId === "string" ? snowflake.parse(req.query.officerId) : null, 500) }); } catch (error) { next(error); } });
policePatrolReportsRouter.get("/bot/channels/due", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); res.json({ reports: await listPolicePatrolChannelsDue(botId) }); } catch (error) { next(error); } });
policePatrolReportsRouter.post("/bot/reports/:reportId/channel-cleared", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); await clearPolicePatrolChannel(botId, id.parse(req.params.reportId)); res.json({ ok: true }); } catch (error) { next(error); } });
policePatrolReportsRouter.post("/bot/reports/:reportId/delete", requireBot, async (req, res, next) => { try { const botId = await botIdFor(req); await licensed(botId); const input = z.object({ actorId: snowflake }).parse(req.body); const report = await deletePolicePatrolReport(botId, id.parse(req.params.reportId), input.actorId); if (!report) throw routeError("Relatório não encontrado.", 404); res.json({ report }); } catch (error) { next(error); } });

async function botIdFor(req: any) { const value = await resolveRequestBotId(req); if (!value) throw routeError("Bot não identificado.", 400); return value; }
async function licensed(botId: string) { const permissions = await getBotApiPermissions(botId); if (!permissions) throw routeError("Bot não encontrado.", 404); if (!permissions.enabledModules.includes(POLICE_PATROL_MODULE_ID)) throw routeError("Relatórios policiais não liberados.", 403); }
async function authorize(user: any, botId: string, guildId: string, manage: boolean) { await licensed(botId); const allowed = manage ? await canUseDevBotModule(user, botId, guildId, POLICE_PATROL_MODULE_ID) : await canReadDevBotModule(user, botId, guildId, POLICE_PATROL_MODULE_ID); if (!allowed) throw routeError("Sem permissão para relatórios policiais.", 403); }
function routeError(message: string, statusCode: number) { return Object.assign(new Error(message), { statusCode }); }
